version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

commands:
  restore_all_caches:
    description: Restore php dependencies
    steps:
      - restore_cache:
          keys:
          - v1-php-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-php-

  xdebug:
    description: Install Xdebug and set coverage mode
    steps:
      - run:
          command: |
            sudo -E install-php-extensions xdebug
            sudo docker-php-ext-enable xdebug
            echo "xdebug.mode = coverage" | sudo tee -a /etc/php.d/circleci.ini

  composer:
    description: Ensure all php dependencies are installed
    steps:
      - run:
          name: Self-update composer
          command: sudo composer self-update

      - run:
          name: Run composer install
          command: composer install --prefer-dist --no-interaction --no-progress

  structure-validation:
    description: Ensure package directory strucure is valid
    steps:
      - run:
          name: Run pds-skeleton validator
          command: vendor/bin/pds-skeleton validate

  php-cs-fixer:
    description: Ensure php code follows style rules
    steps:
      - run:
          name: Run php-cs-fixer
          command: vendor/bin/php-cs-fixer fix --diff --dry-run --verbose --sequential

  security:
    description: Check known security issues in php dependencies
    steps:
      - run:
          name: Audit Composer dependencies
          command: composer audit --locked

  save_all_caches:
    description: Save php and javascript dependencies
    steps:
      - save_cache:
          paths:
            - ./vendor
          key: v1-php-{{ checksum "composer.lock" }}

jobs:
  build:
    parameters:
      php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>
    environment:
      APP_ENV: "testing"
    steps:
      - checkout
      - restore_all_caches
      - xdebug
      - composer
      - structure-validation
      - php-cs-fixer
      - security
      - save_all_caches
      # test
      - run:
          name: Run phpunit
          command: vendor/bin/phpunit --coverage-clover clover.xml
      - codecov/upload

workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              php-version: ["8.3", "8.4", "8.5"]
